# .github/workflows/ci-cd.yaml

name: CI/CD Pipeline

# Trigger the workflow on push to main and develop branches, and on pull requests
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

# Global environment variables
env:
  NODE_VERSION: '18.x'

jobs:
  # Lint & Test Job - Runs on all triggers
  build-and-test:
    name: Build & Test
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Install Frontend Dependencies
      run: |
        cd frontend
        npm ci

    - name: Build Frontend
      run: |
        cd frontend
        npm run build

    - name: Install Backend Dependencies
      run: |
        cd backend
        npm ci

    - name: Run Backend Tests
      run: |
        cd backend
        npm test

    - name: Run Frontend Tests
      run: |
        cd frontend
        npm test